version: "3.9"

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: todo-ws-app:develop
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@1234
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    container_name: todo_web

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@1234
    container_name: todo_db

  redis:
    image: redis:6-alpine
    container_name: todo_redis

volumes:
  postgres_data:
